### ISSUE TITLE
Blender Crashes on using the Auto Convex button.

### ISSUE THREAD

**Issue by JacobDSiler** [Weisl/Collider-Tools#303]
Here is a Screenshot: 
![image](https://user-images.githubusercontent.com/46026740/207299803-7aed6ac6-656f-4aa1-b5f3-ed7269316c27.png)

**Comment by JacobDSiler** [comment]
I am using 2.93.6. I haven't entered the license key anywhere as I can't
figure out where to put it, so that may be my actual mistake. I just
noticed the other buttons cause the same crash.
It is most likely my own confusion causing the issue. Where do I enter the
license key?

**Comment by Weisl** [comment]
I can see how much work it would be to use the old exporter as a fallback for older blender versions.

**Comment by Weisl** [comment]
Every blender version from 3.2 and before is affected by this crash.

**Comment by JacobDSiler** [comment]
I tried 1.1 just now, and the crash happens there too. Unfortunately, it appears to happen on all the buttons. I bought it for the Auto Convex button initially so that was the only one I noticed. Is there any other addon required to be enabled to use Collider Tools?

**Comment by JacobDSiler** [comment]
Okay, I uninstalled both versions, and reinstalled 1.1 and restarted, and it works now. The GUI and options don't seem quite as sophisticated, but it works and I'm really happy it does. Thanks for your help!

**Comment by Weisl** [comment]
Glad that it worked and thanks for letting me know! I was testing what the issue could be. Version 1.2 uses a new version of auto convex but it requires a different exporter. I will continue to look into a fallback for older blender versions :). But happy that it works for now.

**Comment by Weisl** [comment]
Made a version that uses the old exporter for older blender versions. Here 2.93
https://user-images.githubusercontent.com/6353016/207603172-2efdb400-790a-41b8-8254-8292cf0101eb.mp4
