### ISSUE TITLE
ModuleNotFounderror How to fix ? 

### ISSUE THREAD

**Issue by SanTum1** [Weisl/Collider-Tools#451]
![image](https://github.com/Weisl/Collider-Tools/assets/117443131/bba53e38-8b25-48ac-91a1-f71e3b9be01e)

**Comment by Weisl** [comment]
Hi, 
I guess you are using the addon directly from Github? This appears when it is not packaged correctly. This should not happen on the versions on Gumroad or Blender Market.

**Comment by SanTum1** [comment]
Yes, I downloaded the addon from a direct link with versions
And you had to download the main page of the addon
Thank you, it works!
