### ISSUE TITLE
Scaling one axis resulting issues

### ISSUE THREAD

**Issue by KoZ3D** [Weisl/Collider-Tools#452]
I've got an issue: Scaling object makes collision scale wrong axis
Collision primitives (except ucx) has transforms. No way to change it.
The top collision made using default blender box, bottom ones are made using collider tools.

https://github.com/Weisl/Collider-Tools/assets/131483381/93afcdcf-6ff8-4a01-bed6-205bc6368084

**Comment by Weisl** [comment]
This is very interesting I will need to investigate this further!

**Comment by Weisl** [comment]
I can confirm this bug. I will probably not be able to solve this completely as there are some settings on export/import that ar hard for me to control but I can probably provide tools to fix this issue when needed or minimize the risk of this happening.

**Comment by Weisl** [comment]
@KoZ3D 
I could solve it in a first test by changing the origin rotation of the collider by 90 on the collider.
![image](https://github.com/Weisl/Collider-Tools/assets/6353016/d1a3bf77-002e-4577-80ee-070aa1a23dc8)

**Comment by KoZ3D** [comment]
i've just tried this, but result still the same. (screen with and without 90dgr rotation)
even converting to stl and back to fbx resulting same results
![изображение](https://github.com/Weisl/Collider-Tools/assets/131483381/50ac580b-026a-4204-b26d-83c9e44ee76f)

**Comment by KoZ3D** [comment]
Joining and then spliting collision primitives to default cubes also affect their behaves : 0

**Comment by Weisl** [comment]
I still have not been able to reproduce this. I am closing it for now. Let's see if it appears for any other version.
