### ISSUE TITLE
On the functionality of the plugin in the blender 4.0 version.

### ISSUE THREAD

**Issue by MaaximGL** [Weisl/Collider-Tools#453]
Do you have plans to upgrade the plugin to Blender 4.0 ?

up:: At the moment, the plugin does not turn on or blender is being painted.

**Comment by Weisl** [comment]
Are you using the Github version or a version from Blender Market\ Gumroad? Can you provide a screenshot? It is working for me

**Comment by Weisl** [comment]
THere is an issue with convex hull for blender 4.0

**Comment by Weisl** [comment]
![2023_11_22_11_16_42_Unsaved_Blender_4 0](https://github.com/Weisl/Collider-Tools/assets/6353016/c11f8deb-dc4a-4c3e-ad15-972e5a7e5ce9)

**Comment by MaaximGL** [comment]
![image](https://github.com/Weisl/Collider-Tools/assets/66566859/30ea56cf-3884-47b6-8854-1f6e68ac7bfe)
I have the c version of github. A friend of mine purchased a version on the blender market, but he has the same problem with importing the plugin in 4.0.
@Weisl

**Comment by Weisl** [comment]
Thanks for the screenshot and report. I will investigate this soon - hopefully today and try to provide an update as soon as possible

**Comment by Weisl** [comment]
@MaaximGL. This error is from wrong packaging the official collider module is not named 'Collider-Tools-1'
There will be an update for Blender 4.0 but it will not fix this issue.

**Comment by MaaximGL** [comment]
@Weisl This happens because the folder inside the archive is called "Collider-Tools-1.4.1". Blender does not perceive the names of addons with dots. The dots should be replaced with "_" or "-"

**Comment by MaaximGL** [comment]
![image](https://github.com/Weisl/Collider-Tools/assets/66566859/b6f820d7-ca4f-49cf-bd7d-bbd87c506e27)
In the new version 1.4.2, there is a problem with the "oriented Minimum BBox". The blender also crashes. Everything else seems to work.

**Comment by Weisl** [comment]
The version on blendermarket and gumroad does not have dots in the folder name. I just double checked!

**Comment by Weisl** [comment]
I can confirm that minimal bounding box is broken. I will fix that.

**Comment by Weisl** [comment]
BBox crash is fixed in version 1.4.3
https://github.com/Weisl/Collider-Tools/issues/455
