### ISSUE TITLE
Not running in Blender 4.0.2

### ISSUE THREAD

**Issue by castelblends** [Weisl/Collider-Tools#480]
Hi, 

1.4 worked fine in Blender 3.6.5, moved to Blender 4.0.2 and it fails to generate. Upgraded to 1.5 and gets installed but it won't become an active add-on, every time I check it comes back with this error. 

![Screenshot 2024-03-07 091842](https://github.com/Weisl/Collider-Tools/assets/61828683/5cfbbec1-c460-49e1-ab09-73ef5d4547b9)

Went back to 3.6.5 and tried to install 1.5 and 1.4.3 and got this as well
![Screenshot 2024-03-07 093112](https://github.com/Weisl/Collider-Tools/assets/61828683/eb9b190e-f89d-473c-8cbb-8bbacb5a6e8f)

Thanks.

**Comment by Weisl** [comment]
Install the supported version from Gumroad or Blender market. Also make sure to remove the do a clean install

- Remove the addon
- Restart Blender
- Install fresh version

**Comment by castelblends** [comment]
got it from Blendermarket, running fine now. Thanks.
