### ISSUE TITLE
[Request] Generation of occlusion meshes

### ISSUE THREAD

**Issue by xCuri0** [Weisl/Collider-Tools#482]
Is this currently possible to do with Collider Tools ?

Currently I'm just making occlusion boxes manually

**Comment by Weisl** [comment]
I am not sue what you mean with occlusion boxes.

**Comment by xCuri0** [comment]
Something like this
![image](https://github.com/Weisl/Collider-Tools/assets/29529557/1b167116-933c-43ce-a82f-eb99cde34561)


The white box is used by the game engine to tell it not to draw anything behind it.

**Comment by Weisl** [comment]
Will not be supported.
